### ISSUE TITLE
Please I need help with this

### ISSUE THREAD

**Issue by ghost** [simonblais/BingoCardGenerator#1]
I don't have the image files so I get an error

**Comment by simonblais** [comment]
The script is designed to use your own image files, they must be placed in the following folder:
<directory of python script>/images/squares

**Comment by ghost** [comment]
yes but I get this error :

```
Generating 1 cards with 24 indices each
Traceback (most recent call last):
  File "main.py", line 131, in <module>
    result = generateCardImage(indices, imagePaths, nbRows, nbCols, skipMiddle, bgPaths, squarePositions);
  File "main.py", line 53, in generateCardImage
    src = Image.open(imagePaths[index]);
IndexError: list index out of range
```
Please share your base files with me, I will love you so much

**Comment by pribaq** [comment]
hello?
